hydra:
  run:
    dir: 'data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}'

_target_: diffusion_policy.workspace.train_diffusion_unet_hybrid_workspace.TrainDiffusionUnetHybridWorkspace
action_dim: 7
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-mse_error_val={mse_error_val:.3f}.ckpt
    k: 5
    mode: min
    monitor_key: mse_error_val
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
critic_target:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: obs_global_rerun
horizon: 16
keypoint_dim: 3
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: 2023.02.25-03.06.09_train_diffusion_unet_image_franka
  project: diffusion_policy_debug
  resume: true
  tags:
  - train_diffusion_unet_image
  - obs_global_rerun
multi_run:
  run_dir: data/outputs/2023.02.25/03.06.09_train_diffusion_unet_image_franka_real
  wandb_name_base: 2023.02.25-03.06.09_train_diffusion_unet_image_franka_real
n_action_steps: 8
n_latency_steps: 0
n_obs_steps: 4
name: train_diffusion_unet_image_franka
obs_as_global_cond: true
obs_as_local_cond: false
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06
critic_optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06
past_action_visible: false
eps_lagrange_constraint_mse_predictions: 0.00025
lagrange_optimizer:
  _target_: torch.optim.AdamW
  betas:
    - 0.95
    - 0.999
  eps: 1.0e-08
  lr: 0.001
  weight_decay: 1.0e-06
policy:
  _target_: diffusion_policy.policy.diffusion_unet_hybrid_image_policy.DiffusionUnetHybridImagePolicy
  eta_coeff_critic: 0.001
  cond_predict_scale: true
  crop_shape: [216, 216]
  diffusion_step_embed_dim: 128
  down_dims:
    - 512
    - 1024
    - 2048
  eval_fixed_crop: true
  horizon: 16
  kernel_size: 5
  n_action_steps: 8
  n_obs_steps: 4
  n_groups: 8
  shape_meta:
    action:
      shape:
        - 7
    obs:
      camera_1:
        shape:
#          - 4  # TODO
          - 3
          - 240
          - 240
        type: rgb
      eef:
        shape:
         - 7
        type: low_dim
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    num_train_timesteps: 100
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    variance_type: fixed_small # Yilun's paper uses fixed_small_log instead, but easy to cause Nan
    clip_sample: True # required when predict_epsilon=False
    prediction_type: epsilon # or sample
  num_inference_steps: 100
  obs_as_global_cond: true
  obs_encoder_group_norm: true
critic:
  _target_: diffusion_policy.model.diffusion.conditional_unet1d_critic.DoubleCritic
  n_action_steps: 8
  horizon: 16
  cond_predict_scale: true
  diffusion_step_embed_dim: 128
  down_dims:
    - 256
    - 512
    - 1024
  kernel_size: 5
  n_obs_steps: 4 # TODO: put back to 2?
  n_groups: 8
  shape_meta:
    action:
      shape:
        - 7
    obs:
      camera_1:
        shape:
#          - 4  # TODO
          - 3
          - 240
          - 240
        type: rgb
      eef:
        shape:
          - 7
        type: low_dim
  obs_as_global_cond: true
  gamma: 0.99

pred_action_steps_only: false
task:
  abs_action: true
  dataset:
    _target_: diffusion_policy.dataset.real_franka_image_dataset.RealFrankaImageDataset
#    abs_action: true
    shape_meta:
      action:
        shape:
          - 7
      obs:
        camera_1:  # TODO: change back to camera_0
          shape:
  #          - 4  # TODO
            - 3
            - 240
            - 240
          type: rgb
        mass:
          shape:
            - 256 # after RFF
          type: low_dim
        eef:
          shape:
            - 7
          type: low_dim
      label:
        shape:
          - 1
        type: low_dim
#    dataset_path: /home/ros/humble/src/diffusion_policy/data/smaller_dataset
#    dataset_path: /home/sony-unicorn/ros/humble/src/diffusion_policy/data/fake_puree_experiments/diffusion_policy_dataset/
    dataset_path: /home/lucagrillotti/ros/humble/src/diffusion_policy/data/fake_puree_experiments/diffusion_policy_dataset_exp2_v2/
#    dataset_path: /home/ros/humble/src/diffusion_policy/data/fake_puree_experiments/diffusion_policy_dataset_exp2_v2/  # TODO
    dt: 0.1
    horizon: 16
    n_obs_steps: 4
    n_action_steps: 8
    pad_after: 7
    pad_before: 1
#    robot_noise_ratio: 0.1
    seed: 42
    val_ratio: 0.02
    delta_action: false
    use_cache: true
    mass_encoding_size: 256
    period_adjustment_rff: 0.15
    proba_diffusion_remove_mass_label: 0.2
  env_runner:
    _target_: diffusion_policy.env_runner.real_robot_runner.DummyImageRobot
task_name: kitchen_lowdim
training:
  checkpoint_every: 5  # Needs to be a multiple of sample_every
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 8000
  resume: true
  rollout_every: 50
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 5
val_dataloader:
  batch_size: 16
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: false
dataloader:
  batch_size: 64
  num_workers: 30
  persistent_workers: false
  pin_memory: true
  shuffle: true
