_target_: diffusion_policy.workspace.train_diffusion_unet_lowdim_workspace.TrainDiffusionUnetImageWorkspace
action_dim: 7
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
    k: 5
    mode: max
    monitor_key: test_mean_score
dataloader:
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: true
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: obs_global_rerun
horizon: 16
keypoint_dim: 3
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: 2023.02.25-03.06.09_train_diffusion_unet_lowdim_kitchen_lowdim
  project: diffusion_policy_debug
  resume: true
  tags:
  - train_diffusion_unet_image
  - obs_global_rerun
multi_run:
  run_dir: data/outputs/2023.02.25/03.06.09_train_diffusion_unet_image_franka_real
  wandb_name_base: 2023.02.25-03.06.09_train_diffusion_unet_image_franka_real
n_action_steps: 8
n_latency_steps: 0
n_obs_steps: 2
name: train_diffusion_unet_image
obs_as_global_cond: true
obs_as_local_cond: false
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.diffusion_unet_hybrid_image_policy.DiffusionUnetHybridImagePolicy
  cond_predict_scale: true
  crop_shape:
    - 216
    - 288
  diffusion_step_embed_dim: 128
  down_dims:
  - 512
  - 1024
  - 2048
  eval_fixed_crop: true
  horizon: 16
  kernel_size: 5
  n_action_steps: 8
  n_obs_steps: 2
  n_groups: 8
  shape_meta:
    action:
      shape:
        - 7
    obs:
      camera_0:
        shape:
          - 3
          - 240
          - 320
        type: rgb
      camera_1:
        shape:
          - 3
          - 240
          - 320
        type: rgb
      camera_2:
        shape:
          - 3
          - 240
          - 320
        type: rgb
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddim.DDIMScheduler
    num_train_timesteps: 100
    beta_start: 0.0001
    beta_end: 0.02
    # beta_schedule is important
    # this is the best we found
    beta_schedule: squaredcos_cap_v2
    clip_sample: True
    set_alpha_to_one: True
    steps_offset: 0
    prediction_type: epsilon # or sample
  num_inference_steps: 100
  obs_as_global_cond: true
  obs_encoder_group_norm: true
pred_action_steps_only: false
task:
  abs_action: true
  dataset:
    _target_: diffusion_policy.dataset.kitchen_mjl_lowdim_dataset.KitchenCustomDataset
    abs_action: true
    dataset_dir: data/kitchen/kitchen_demos_multitask/cartesian_control_all
    horizon: 16
    pad_after: 7
    pad_before: 1
    robot_noise_ratio: 0.1
    seed: 42
    val_ratio: 0.02
    use_xyz: false
    use_end_effector: true
  env_runner:
    _target_: diffusion_policy.env_runner.real_robot_runner.DummyRobot
task_name: kitchen_lowdim
training:
  checkpoint_every: 50
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 8000
  resume: true
  rollout_every: 50
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 1
val_dataloader:
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: false
